# Generated by Django 6.0.4 on 2026-08-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0002_delete_categoria_delete_producto_delete_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoProveedor',
        ),
    ]
