# Generated by Django 6.0.4 on 2026-05-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CATEGORIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'STOCK_SUCURSAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_suc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'SUCURSAL',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
