# Generated by Django 6.0.4 on 2026-08-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id_enlace', models.AutoField(primary_key=True, serialize=False)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PRODUCTO_PROVEEDOR',
                'managed': False,
            },
        ),
    ]
