# Generated by Django 6.0.4 on 2026-05-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_proveedor_stocksucursal_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='PRODUCTO',
        ),
    ]
