# Generated by Django 6.0.4 on 2026-06-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_mov', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Traslado', 'Traslado')], max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MOVIMIENTO',
                'managed': False,
            },
        ),
    ]
