# Generated by Django 6.0.4 on 2026-06-01 03:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del rol (ej: Administrador, Empleado).', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol.')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(help_text='Nombre completo del usuario.', max_length=100)),
                ('email', models.EmailField(help_text='Email del usuario. Debe ser único', max_length=254, unique=True)),
                ('dni', models.CharField(help_text='Número de documento, tiene que ser único y tener entre 7 u 8 dígitos.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$')])),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='usuarios.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
