# Generated by Django 6.0.4 on 2026-04-20 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol',
            new_name='Role',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del usuario.', max_length=100)),
                ('email', models.EmailField(help_text='Email del usuario. Debe ser único', max_length=254, unique=True)),
                ('dni', models.CharField(help_text='Número de documento, tiene que ser único y tener entre 7 u 8 dígitos.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$')])),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento.')),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='usuarios.role')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
